# Generated by Django 2.2.3 on 2019-07-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('auth_code', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('payment_card_token', models.CharField(max_length=255)),
                ('mid', models.CharField(max_length=255)),
                ('third_party_id', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=5)),
            ],
        ),
    ]
