# Generated by Django 2.2.3 on 2019-07-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(default='visa', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='auth_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(choices=[('GBP', 'pound sterling'), ('USD', 'US dollar'), ('EUR', 'euro')], max_length=5),
        ),
    ]
